@ConnectMauiTonet8ApiDefaultAuthnticationendpoint_HostAddress = http://localhost:5085

GET {{ConnectMauiTonet8ApiDefaultAuthnticationendpoint_HostAddress}}/weatherforecast/
Accept: application/json

###
